### ISSUE TITLE
Progress bar doesn't work when attempting to download software asyn

### ISSUE THREAD

**Issue by mshafer1** [JamieSinn/CSA-USB-Tool#6]
I might not be using this right:

Open exe (no arguments)
Select Download Folder
check Download Async
click download

Seams to hang and the progress bar only partially grows (and then empties)
![2018-02-24_19-09-20](https://user-images.githubusercontent.com/2565361/36636940-5ecbd5fc-1996-11e8-9664-836000d174f4.png)

**Comment by JamieSinn** [comment]
So the reason for this is that the progress bar is actually being updated by each thread downloading software.

When downloading async there would need to be a progress bar for each software being downloaded, and since the software list is dynamic, it seems to flash/hang depending on which software last updated it.

The NI update and labview cause it to seem like it's stalled, as they're 800MB and 4GB respectively. 

Currently this is as intended, but I may change it in the future.

**Comment by JamieSinn** [comment]
Here's a better recording of how it's intended to work:
https://gfycat.com/KeenInsecureBuffalo

**Comment by mshafer1** [comment]
Thanks for the clarification
